[package]
name = "aws_event_stream_parser"
version = "0.0.1"
license = "MIT"
readme = "readme.md"
description = "Rust implementation of the vnd.amazon.event-stream binary format"
repository = "https://github.com/emblica/aws-event-stream-parser-rs"
authors = ["Teemu Heikkilä <teemu@emblica.fi>"]
edition = "2018"

[dependencies]
nom = "5.0.0-beta2"
crc = "^1.0.0"
byteorder = "1"
chrono = "0.4"
uuid = "0.7.4"

[dev-dependencies]
hex-literal = "0.2.0"
